heat_template_version: 2013-05-23

description: Deploy An Openstack-Ansible Private Cloud on Rackspace Public Cloud

parameters:
  osa_release:
    type: string
    label: OpenStack-Ansible Release
    description: A branch, tag, or SHA to work from
    default: 'master'
  osa_repo:
    type: string
    label: OpenStack-Ansible Repo
    description: A repository containing OpenStack-Ansible
    default : 'https://github.com/openstack/openstack-ansible.git'
  aio_flavor:
    type: string
    label: AIO Node Flavor
    default: '7'
  keypair:
    type: string
    label: Keypair
  user_vars_url:
    type: string
    label: Provided User Variables File
    description: An optional url to download a user_variables.yml file from (e.g. raw url from paste.openstack.org)
    default : 'false'

resources:
  cloud_config_aio1:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        output:
          all: '| tee -a /var/log/cloud-init-output.log'
        apt_upgrade: true
        packages:
          - curl
          - fail2ban
          - tmux
          - htop
          - multitail
          - vim
          - git-core
        write_files:
          - path: /opt/cloud/runcmd-bash
            permissions: "0700"
            content:
              str_replace:
                template: |
                  #!/bin/bash
                  export HOME="/root"
                  set -e
                  set -x
                  cd /opt
                  git clone %osa_repo% -b %osa_release% || exit_failure "Git Clone Failure"
                  USER_VARS_FILE=%user_vars_url%
                  cd openstack-ansible
                  scripts/bootstrap-ansible.sh >> /opt/cloud/bootstrap-ansible.log 2>> /opt/cloud/bootstrap-ansible.err
                  scripts/bootstrap-aio.sh >> /opt/cloud/bootstrap-aio.log 2>> /opt/cloud/bootstrap-aio.err
                  if [[ ${USER_VARS_FILE} -ne "false" ]]; then
                      curl ${USER_VARS_FILE} -o /etc/openstack_deploy/user_variables.yml
                  fi
                  cd playbooks
                  openstack-ansible setup-everything.yml >> /opt/cloud/setup-everything.log 2>> /opt/cloud/setup-everything.err
                params:
                  "%osa_release%":         { get_param: "osa_release" }
                  "%osa_repo%":            { get_param: "osa_repo" }
                  "%user_vars_url%":       { get_param: "user_vars_url" }
        runcmd:
          - tmux new-session -s osa-heat-multi -d
          - tmux rename-window deploy
          - tmux select-window -t deploy
          - tmux send-keys "touch /opt/cloud/runcmd-bash.err /opt/cloud/runcmd-bash.log /opt/cloud/bootstrap-ansible.err /opt/cloud/bootstrap-ansible.log /opt/cloud/bootstrap-aio.err /opt/cloud/bootstrap-aio.log /opt/cloud/setup-everything.err /opt/cloud/setup-everything.log" C-m
          - tmux send-keys "/opt/cloud/runcmd-bash >> /opt/cloud/runcmd-bash.log 2>> /opt/cloud/runcmd-bash.err" C-m

  server_aio1:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "osa-aio1-%heat_stack_prefix%"
          params:
            "%heat_stack_prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      flavor: { get_param: "aio_flavor" }
      image: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
      key_name: { get_param: keypair }
      config_drive: True
      user_data_format: RAW
      user_data: { get_resource: cloud_config_aio1 }

outputs:
  server_aio1_ip:
    description: AIO1 IP
    value: { get_attr: [ server_aio1, accessIPv4 ] }
